return {
    -- ── Unreleased dev ────────────────────────────────────────────────────────
    -- Always the first entry. Append a bullet for every dev.NN iteration here.
    -- publish_stable.sh promotes this block into a named stable release and
    -- inserts a fresh empty dev entry above it. Do NOT copy bullets by hand.
    -- The @DEV markers below are parsed by tools/promote_changelog.py - keep them.
    --@DEV_START
    {
        version = "dev",
        date    = "2026-09-10",
        channel = "dev",
        changes = {
            "Distribution: the separate dev branch is gone; the dev update channel and the installer now follow main, so PRs merged into main reach OTA clients immediately. Machines installed before this change keep the old dev URL in /.mineboom_source and must switch the source in Settings > Connections or be reinstalled",
            "Fixes: App Store channel toggle hit zone was off by one column; Logs no longer duplicates entries on every open and unsubscribes its listener on close; log lines now carry the source in brackets so a message's first word is not parsed as its source; Admin could delete a user by clicking the header row while scrolled; HTTP timeout is now passed in the table form CC:Tweaked actually honours; auto-lock timer is reset only by user input, not by rednet/http/timer events; app ids from the store are validated before being written to /os/apps and Admin accepts the store catalog only from the configured store computer",
            "Connections: distributions now describe their app catalog and dev/stable URLs so standalone installs can browse apps and switch update channels; added an admin Connections screen, optional service discovery and explicit shared-account server selection with separate sessions/cache/data and local-owner recovery. Older releases without standalone/connection support are blocked before installation (dev.45)",
            "Standalone setup: new installations keep their own device profile outside OTA files, skip the world registry and preconfigured server IDs, and create a local owner on first boot; existing installations retain their legacy configuration. Installer source choices are explicit, and OS Update no longer invents channel URLs for custom sources (dev.44)",
            "App Store: the Store tab now has a source switcher (Rednet / Local / Web) so apps can be installed either from the in-game store computer over Rednet or over HTTP from a local or internet host, using the same mechanism as OS updates; the choice is remembered in /.appstore_source",
            "App Store: HTTP catalog and app downloads run in a background worker (ctx.spawn), so the clock keeps ticking and clicks are not lost while downloading",
            "App Store: Rednet replies are now accepted only from the configured store computer, so another computer can no longer answer first and push app code onto the machine",
            "App Store: the store computer number now lives in one place - storeComputer in the config - because the Local URL takes it from an {id} placeholder instead of hardcoding it twice",
            "Updater: the manifest is now split into a core set plus one set per role, so a machine downloads only what its role runs - a server drops from ~497 KB to ~70 KB and pocket computers stop fetching server roles they never launch; manifest.files is still published as the full union so older clients can keep updating",
            "Installer: install.lua now takes a role as its second argument (install.lua <url> <role>), installs just that role's files and records the choice in /.mineboom_role, which boot.lua then uses to register the machine under the right role instead of the default one",
            "Installer: running install.lua with no arguments is now an interactive menu - pick the channel (stable, dev or a custom URL), then what the computer is for, with a file count and one-line description per role read from the manifest, then a summary to confirm before anything is written; passing arguments still installs silently as before",
            "Installer: after a successful install it removes files left over from the previous one (for example the shell and system apps when a machine becomes a server), reclaiming ~430 KB on a server. The list comes from the old manifest, so apps installed from the App Store are never touched",
            "App Store server: replaced the standalone script on computer 19 with a MineboomOS role (app_server), so the store now gets OTA updates, shared modem discovery, logging and safe mode like every other machine; it also keeps apps/index.gen.lua up to date so HTTP clients detect changed app files by checksum instead of relying on a hand-bumped version",
        },
    },
    --@DEV_END
    {
        version = "1.0.6 Obsidian",
        date    = "2026-06-02",
        channel = "stable",
        changes = {
            "PocketOS: added a background coroutine scheduler (ctx.spawn/ctx.refresh) so apps can run blocking I/O without freezing the UI; OS Update now downloads in the background showing live N/M progress while the clock and screen stay responsive",
            "Boot: registry contact is now asynchronous with a short timeout (4s) and a skip-on-keypress prompt, so an unreachable registry server no longer hangs startup for ~20-30s; boot shows live registry/registration status",
            "Launcher: installed user apps (e.g. Snake) no longer vanish after a reboot - boot now treats the presence of the app file in /os/apps as the source of truth and ignores the stale global /data/apps_removed.db, which the per-user install/uninstall flow no longer maintains",
        },
    },
    {
        version = "1.0.5 Obsidian",
        date    = "2026-05-31",
        channel = "stable",
        changes = {
            "Apps and Admin: switched installed-app metadata reads to safe static M.* parsing, so Manage and Perms classify apps automatically without running app files; fixed Admin Perms category toggle dropping allowed apps missing from the loaded App Store catalog, which made installed apps (e.g. Snake) vanish from the launcher",
            "Launcher: groups apps with the same category fallback as Apps and Admin, so an app lands in the same category on every screen (Apps, launcher, Manage, Perms)",
            "Network: added shared modem auto-discovery, so PocketOS, Lab and User Server can open Rednet from the actual modem side instead of requiring the configured side",
            "Users: remote user data is now cached locally in /data/users_cache.db and reused for offline login when Rednet or the user server is unavailable",
            "UI: login, lock screen and desktop status now show offline mode when the cached user database is being used",
            "Auth UI: numeric keyboard input now works for lock screen unlock, login/register PIN entry, Settings password changes and Admin user password edits; Space now confirms password/PIN entry the same way as Enter",
            "Lock screen: now acts as a simple device lock overlay - tap/click anywhere to dismiss it, returning remembered users to desktop and non-remembered users to login with no PIN prompt",
            "Files: fixed crash when running a .lua script (shell global is unavailable in app context; replaced with os.run)",
            "Login: removed Register button; new users are created by the admin via the Admin app",
            "Admin: user list now has a scrollbar (wheel, click-to-page and thumb drag) so Edit/Perms/Del stay reachable with more than ~5 users; the Perms app list gained the same scrollbar",
            "PocketOS: fixed saved text scale not being applied after reboot/login; the UI now uses the user's stored desktop scale immediately",
        },
    },
    {
        version = "1.0.4 Obsidian",
        date    = "2026-05-31",
        channel = "stable",
        changes = {
            "Games: added 2048",
            "Admin Perms: All apps toggle now restores the previously selected apps when turned back off; added Clear button (right edge of the All-apps row) with a confirmation dialog; category headers now have a tri-state checkbox to allow/block a whole app category at once (arrow/label still expands/collapses); fixed perms crash where categoryState was used before its definition",
            "Fixed crash when pressing Logout in the launcher (doLogout was an out-of-scope nil global)",
        },
    },
    {
        version = "1.0.3 Obsidian",
        date    = "2026-05-30",
        channel = "stable",
        changes = {
            "Clock: unified time source for all screens (os/lib/clock.lua) - Real or Minecraft mode with UTC offset, fixes lockscreen time desync",
            "Clock: lockscreen and home dashboard redraw on the clock timer so Minecraft time stays live; app screens still redraw only when the displayed minute changes",
            "Settings: Time mode toggle (Real / Minecraft) and UTC offset cycler (offset hidden in Minecraft mode)",
            "Terminal: now admin-only - it grants a full CraftOS shell, so it is hidden from regular users and from permission lists",
            "Login: shows last logged-in user first; version read live from manifest; fixed arrow hit area",
            "Taskbar: shows current user name; desktop no longer displays the modem side",
            "Admin > Perms: app list auto-parsed with names and categories (collapsible), mirroring the Apps app",
            "Admin > Perms: now lists the full App Store catalog (incl. apps not installed on this computer) by querying the store server, so permissions are identical on every machine and toggling no longer silently blocks uninstalled apps",
            "Fixed crash on logout (userCanSeeApp scope bug)",
        },
    },
    {
        version = "1.0.2 Obsidian",
        date    = "2026-05-29",
        channel = "stable",
        changes = {
            "OS Update: fixed buttons not responding after app open (HTTP call was blocking event queue)",
            "OS Update: channel switcher stable/dev available to all users (was admin only)",
            "OS Update: separate Check and Update buttons; Update no longer checks without user action",
            "OS Update: changelog viewer with word wrap, scrollbar and collapsible version sections",
            "Updater: .mineboom_source now takes priority over config osSourceUrl, fixes alternating channel bug on reboot",
            "Notifications: added Clear all button to notification panel footer",
            "Settings > About: version and channel now read live from disk, not from boot-time cache",
            "Settings > About: added Channel field showing dev or stable",
            "Settings > About: long values wrap to next line instead of truncating at screen edge",
            "Stable versioning: named release scheme introduced (1.0 Obsidian, 1.0.1 Obsidian, ...)",
        },
    },
    {
        version = "1.0 Obsidian",
        date    = "2026-05-29",
        channel = "stable",
        changes = {
            -- OS Shell & Desktop
            "MineboomOS is a full windowing OS for CC:Tweaked pocket computers and advanced monitors",
            "Desktop with customizable wallpaper patterns and icon grid for recent apps",
            "Taskbar shows running apps, clock, volume indicator and notification bell",
            "Launcher: full-screen app list with categories (Automation, Network, Games, System) and search",
            "10 built-in color themes selectable from Settings or system tray",
            "Text scale adjustment for monitors and large displays",
            "Boot splash screen showing OS version and computer label",
            "Black-frame transition animation between screens",
            -- Multi-user & Security
            "Multi-user system: each computer supports multiple named accounts",
            "Login screen with numeric keypad (touch-friendly) and keyboard input",
            "New user registration directly from the login screen",
            "Per-user data isolation: each user has their own desktop, app data and settings",
            "Admin role with full access; regular users have configurable restrictions",
            "File permissions per user: allow or deny creating, editing and deleting files",
            "App install permission: control who can install apps from the store",
            "App visibility control: restrict which apps a user can see and launch",
            "Remember me: optional session persistence across reboots",
            "Auto-lock timer: configurable idle timeout (1, 5, 10, 30 min or never)",
            "Lock screen with large clock; tap or click to unlock",
            "Centralized user database on a dedicated server computer (computer 23)",
            "User data synced across all computers via Rednet (user_server protocol)",
            -- System Apps
            "Settings app: categorized (Appearance, Display, Sound, Account, System)",
            "Settings: theme picker, wallpaper picker, modem side selector",
            "Settings: clock format (12h/24h), sound toggle, volume slider",
            "Settings: change password, lock now, logout, OS update shortcut",
            "Settings > About: live OS version, channel, computer ID, label, free space",
            "Files app: browse filesystem, create files and folders, rename, delete",
            "Files app: permission-aware (respects editFiles/deleteFiles per user)",
            "Terminal app: interactive Lua shell (admin only by default)",
            "Logs app: view OS event log with timestamps",
            "Admin app: create, edit and delete users; set passwords and permissions",
            "OS Update app: check and install OTA updates over HTTP",
            -- App Store
            "Apps app: install user apps from the App Store server (computer 19)",
            "Apps app: manage installed apps, update individual apps, remove apps",
            "Apps app: stable and dev channels per app with channel switching",
            "App Store serves: Factory control, Hub status, Storage browser, RTC",
            "App Store serves: Minesweeper and Snake games",
            -- Network & Integration
            "Factory app: full control panel for the redstone automation network",
            "Hub app: live network status broadcast from the hub server (computer 18)",
            "Storage app: browse and search the RS storage network in real time",
            "RTC app: transfer items from RS storage directly to a chest",
            "Push notifications: any computer can send a toast to a PocketOS device",
            "Push notifications use Rednet protocol pocket_notify",
            "Background services framework: OS-level event handlers with no UI",
            -- Notifications
            "Notification center: bell icon in taskbar shows unread count badge",
            "Toast popups appear at top of screen for incoming notifications",
            "Notification levels: info, warn, error, success (color-coded)",
            "Clear all button in notification panel removes all entries",
            -- Sound
            "Sound system uses the CC:Tweaked speaker peripheral if present",
            "Sound effects: login, lock, app open/close, notifications, errors",
            "Volume control in system tray and Settings; per-user preference saved",
            "Sound can be disabled globally in Settings > Sound",
            -- OTA Updates
            "OTA updater fetches only changed files (checksum comparison)",
            "Atomic staged updates: files downloaded to temp before going live",
            "Stable channel: tested releases (1.0 Obsidian)",
            "Dev channel: latest builds with newest features",
            "Channel switching in OS Update app (admin only)",
            "New computers install stable channel by default via install.lua",
        },
    },
}
