-- Роль: сервер магазина приложений.
--
-- Раздаёт каталог и код приложений по Rednet (протокол pocket_store) и держит
-- рядом с index.lua сгенерированный index.gen.lua с checksum'ами — его читают
-- HTTP-клиенты, которым статик-сервер не может посчитать хеш на лету.
--
-- Каталог живёт на диске этого компьютера: /apps/index.lua плюс файлы, на
-- которые он ссылается. Пути в index.lua заданы относительно корня компьютера
-- ("apps/snake.lua"), поэтому здесь они разворачиваются в абсолютные.
local Loader = dofile("/os/lib/loader.lua")
local FsUtil = dofile("/os/lib/fsutil.lua")
local Modem  = dofile("/os/lib/modem.lua")
local Store  = dofile("/os/lib/store.lua")
local Log    = dofile("/os/lib/log.lua")
local Discovery = dofile("/os/lib/discovery.lua")

local AppServerRole = {}

local DEFAULT_PROTOCOL = "pocket_store"
local DEFAULT_CATALOG  = "/apps"
local INDEX_FILE       = "index.lua"
local GENERATED_INDEX  = "index.gen.lua"
local REGEN_SECONDS    = 30
local RECENT_LIMIT     = 8
local SOURCE           = "app_server"

local function nowSeconds()
    if os.epoch then return math.floor(os.epoch("utc") / 1000) end
    return math.floor(os.clock())
end

-- "apps/snake.lua" -> "/apps/snake.lua"; уже абсолютный путь не трогаем.
local function absPath(p)
    if type(p) ~= "string" or p == "" then return nil end
    if string.sub(p, 1, 1) == "/" then return p end
    return "/" .. p
end

-- ── Каталог ───────────────────────────────────────────────────────────────────

local function loadCatalog(dir)
    local path = dir .. "/" .. INDEX_FILE
    local data = FsUtil.readFile(path)
    if type(data) ~= "string" then
        return {}, "cannot read " .. path
    end

    local catalog, err = Loader.loadTableSandbox(data, "store_index")
    if type(catalog) ~= "table" then
        return {}, tostring(err)
    end

    local out = {}
    for _, entry in ipairs(catalog) do
        if type(entry) == "table" and type(entry.id) == "string" then
            table.insert(out, entry)
        end
    end
    return out
end

-- Одна форма записи и для Rednet-ответа, и для index.gen.lua — так клиент видит
-- одинаковый каталог независимо от транспорта.
local function buildIndex(catalog)
    local apps = {}
    for _, entry in ipairs(catalog) do
        table.insert(apps, {
            id          = entry.id,
            name        = entry.name,
            description = entry.description,
            version     = entry.version,
            category    = entry.category,
            icon        = entry.icon,
            iconBg      = entry.iconBg,
            iconFg      = entry.iconFg,
            file        = entry.file,
            devFile     = entry.devFile,
            devVersion  = entry.devVersion,
            checksum    = Store.fileChecksum(absPath(entry.file)),
            devChecksum = Store.fileChecksum(absPath(entry.devFile)),
        })
    end
    return apps
end

-- Пишем только при реальном изменении: на каждый тик таймера трогать диск незачем.
local function writeGeneratedIndex(dir, apps)
    local path = dir .. "/" .. GENERATED_INDEX
    local data = "-- Generated by the app_server role. Edit index.lua, not this file.\n"
              .. "return " .. textutils.serialize(apps) .. "\n"

    if FsUtil.readFile(path) == data then return false end

    local ok, err = FsUtil.atomicWrite(path, data)
    if not ok then
        Log.warn("cannot write " .. path .. ": " .. tostring(err), SOURCE)
        return false
    end
    return true
end

local function findEntry(catalog, id)
    for _, entry in ipairs(catalog) do
        if entry.id == id then return entry end
    end
    return nil
end

-- Выбирает файл и версию для запрошенного канала, откатываясь на stable, если
-- dev-файла нет на диске.
local function resolveApp(entry, channel)
    local file, version = entry.file, entry.version
    if channel == "dev" and entry.devFile and entry.devFile ~= "" then
        local devPath = absPath(entry.devFile)
        if devPath and fs.exists(devPath) then
            file    = entry.devFile
            version = entry.devVersion or entry.version
        end
    end
    return absPath(file), version
end

-- ── Статус-экран ──────────────────────────────────────────────────────────────

local function drawStatus(st)
    local W, H = term.getSize()
    term.setBackgroundColor(colors.black)
    term.clear()

    term.setCursorPos(1, 1)
    term.setBackgroundColor(colors.blue)
    term.setTextColor(colors.white)
    local title = " APP STORE SERVER"
    term.write(title .. string.rep(" ", math.max(0, W - #title)))

    term.setBackgroundColor(colors.black)
    term.setTextColor(colors.lightGray)
    term.setCursorPos(1, 3); term.write("Computer:")
    term.setCursorPos(1, 4); term.write("Protocol:")
    term.setCursorPos(1, 5); term.write("Modem:")
    term.setCursorPos(1, 6); term.write("Catalog:")
    term.setCursorPos(1, 7); term.write("Served:")

    term.setTextColor(colors.white)
    term.setCursorPos(11, 3); term.write(tostring(st.id) .. "  " .. tostring(st.label or ""))
    term.setCursorPos(11, 4); term.write(tostring(st.protocol))
    term.setCursorPos(11, 5); term.write(tostring(st.modem))
    term.setCursorPos(11, 6); term.write(#st.catalog .. " apps in " .. st.dir)
    term.setCursorPos(11, 7); term.write(st.servedIndex .. " index, " .. st.servedApps .. " apps")

    if st.catalogError then
        term.setTextColor(colors.red)
        term.setCursorPos(1, 8); term.write("Catalog: " .. tostring(st.catalogError))
    end

    term.setTextColor(colors.gray)
    term.setCursorPos(1, 10); term.write("Recent:")
    local y = 11
    for i = #st.recent, 1, -1 do
        if y >= H then break end
        term.setCursorPos(1, y)
        term.setTextColor(colors.lightGray)
        term.write(string.sub(st.recent[i], 1, W))
        y = y + 1
    end

    term.setCursorPos(1, H)
    term.setTextColor(colors.gray)
    term.write(string.sub("R reload catalog  Q quit to shell", 1, W))
end

local function note(st, line)
    table.insert(st.recent, line)
    while #st.recent > RECENT_LIMIT do table.remove(st.recent, 1) end
end

-- ── Обработка запросов ────────────────────────────────────────────────────────

local function send(st, target, msg)
    pcall(rednet.send, target, msg, st.protocol)
end

local function handleIndexRequest(st, senderId)
    -- Перечитываем на каждый запрос: правка index.lua подхватывается без ребута.
    local catalog, err = loadCatalog(st.dir)
    st.catalog, st.catalogError = catalog, err
    send(st, senderId, {type = "store_index", apps = buildIndex(catalog)})
    st.servedIndex = st.servedIndex + 1
    note(st, nowSeconds() .. " index -> " .. senderId)
end

local function handleAppRequest(st, senderId, msg)
    local id      = msg.id
    local channel = msg.channel or "stable"

    if type(id) ~= "string" then
        send(st, senderId, {type = "store_app", id = tostring(id), code = "", error = "Bad request"})
        return
    end

    local entry = findEntry(st.catalog, id)
    if not entry then
        -- Каталог мог обновиться с прошлого запроса индекса — перечитаем и повторим.
        local catalog, err = loadCatalog(st.dir)
        st.catalog, st.catalogError = catalog, err
        entry = findEntry(catalog, id)
    end

    if not entry then
        send(st, senderId, {type = "store_app", id = id, code = "", error = "Unknown app"})
        note(st, nowSeconds() .. " MISS " .. id .. " -> " .. senderId)
        Log.warn("unknown app requested: " .. id, SOURCE)
        return
    end

    local path, version = resolveApp(entry, channel)
    local code = path and FsUtil.readFile(path)
    if type(code) ~= "string" or code == "" then
        send(st, senderId, {type = "store_app", id = id, code = "", error = "App file not found"})
        note(st, nowSeconds() .. " FAIL " .. id .. " -> " .. senderId)
        Log.error("missing file for " .. id .. ": " .. tostring(path), SOURCE)
        return
    end

    send(st, senderId, {
        type    = "store_app",
        id      = entry.id,
        name    = entry.name,
        version = version,
        channel = channel,
        code    = code,
    })
    st.servedApps = st.servedApps + 1
    note(st, nowSeconds() .. " " .. id .. " [" .. channel .. "] -> " .. senderId)
end

-- ── Запуск ────────────────────────────────────────────────────────────────────

function AppServerRole.run(ctx)
    local defaults = (ctx.computers and ctx.computers.pocketosDefaults) or {}
    local perComputer = (ctx.computer and ctx.computer.pocketos) or {}

    local dir = perComputer.storeCatalogDir or defaults.storeCatalogDir or DEFAULT_CATALOG
    dir = (string.gsub(dir, "/$", ""))

    local st = {
        id          = ctx.id,
        label       = ctx.computer and ctx.computer.label,
        protocol    = perComputer.storeProtocol or defaults.storeProtocol or DEFAULT_PROTOCOL,
        dir         = dir,
        catalog     = {},
        recent      = {},
        servedIndex = 0,
        servedApps  = 0,
    }

    local modemSide = perComputer.modemSide
                   or (ctx.computer and ctx.computer.modemSide)
                   or defaults.modemSide
    local modem, err = Modem.open(modemSide)
    if not modem then
        term.setTextColor(colors.red)
        print("App server: cannot open modem: " .. tostring(err))
        Log.error("cannot open modem: " .. tostring(err), SOURCE)
        return
    end
    st.modem = modem

    st.catalog, st.catalogError = loadCatalog(st.dir)
    if st.catalogError then
        Log.warn("catalog: " .. tostring(st.catalogError), SOURCE)
    end
    writeGeneratedIndex(st.dir, buildIndex(st.catalog))

    Log.info("app server ready on " .. st.protocol .. " (" .. #st.catalog .. " apps)", SOURCE)
    drawStatus(st)

    local regenTimer = os.startTimer(REGEN_SECONDS)

    while true do
        local event, p1, p2, p3 = os.pullEvent()

        if event == "rednet_message" then
            local senderId, msg, proto = p1, p2, p3
            Discovery.reply(ctx, senderId, msg, proto, "app_store")
            if proto == st.protocol and type(msg) == "table" then
                if msg.type == "store_request_index" then
                    handleIndexRequest(st, senderId)
                    drawStatus(st)
                elseif msg.type == "store_request_app" then
                    handleAppRequest(st, senderId, msg)
                    drawStatus(st)
                end
            end

        elseif event == "timer" and p1 == regenTimer then
            local catalog, cerr = loadCatalog(st.dir)
            st.catalog, st.catalogError = catalog, cerr
            if writeGeneratedIndex(st.dir, buildIndex(catalog)) then
                note(st, nowSeconds() .. " index.gen updated")
                drawStatus(st)
            end
            regenTimer = os.startTimer(REGEN_SECONDS)

        elseif event == "char" then
            if p1 == "r" or p1 == "R" then
                st.catalog, st.catalogError = loadCatalog(st.dir)
                writeGeneratedIndex(st.dir, buildIndex(st.catalog))
                note(st, nowSeconds() .. " catalog reloaded")
                drawStatus(st)
            elseif p1 == "q" or p1 == "Q" then
                term.setBackgroundColor(colors.black)
                term.setTextColor(colors.white)
                term.clear()
                term.setCursorPos(1, 1)
                print("App server stopped. Reboot to start it again.")
                return
            end
        end
    end
end

return AppServerRole
