local THEMES = {
    {
        name = "BLUE",
        pageBg = colors.black,
        headerBg = colors.blue,
        headerFg = colors.white,
        sectionBg = colors.cyan,
        sectionFg = colors.black,
        columnBg = colors.gray,
        columnFg = colors.white,
        rowA = colors.black,
        rowB = colors.gray,
        rowFg = colors.white,
        lineFg = colors.lightGray,
        mutedFg = colors.lightGray,
        themeButtonBg = colors.blue,
        themeButtonFg = colors.white,
    },
    {
        name = "GREEN",
        pageBg = colors.black,
        headerBg = colors.green,
        headerFg = colors.black,
        sectionBg = colors.lime,
        sectionFg = colors.black,
        columnBg = colors.green,
        columnFg = colors.black,
        rowA = colors.black,
        rowB = colors.gray,
        rowFg = colors.white,
        lineFg = colors.lime,
        mutedFg = colors.lightGray,
        themeButtonBg = colors.green,
        themeButtonFg = colors.black,
    },
    {
        name = "AMBER",
        pageBg = colors.black,
        headerBg = colors.orange,
        headerFg = colors.black,
        sectionBg = colors.yellow,
        sectionFg = colors.black,
        columnBg = colors.orange,
        columnFg = colors.black,
        rowA = colors.black,
        rowB = colors.brown,
        rowFg = colors.white,
        lineFg = colors.yellow,
        mutedFg = colors.lightGray,
        themeButtonBg = colors.orange,
        themeButtonFg = colors.black,
    },
    {
        name = "RED",
        pageBg = colors.black,
        headerBg = colors.red,
        headerFg = colors.white,
        sectionBg = colors.orange,
        sectionFg = colors.black,
        columnBg = colors.red,
        columnFg = colors.white,
        rowA = colors.black,
        rowB = colors.gray,
        rowFg = colors.white,
        lineFg = colors.orange,
        mutedFg = colors.lightGray,
        themeButtonBg = colors.red,
        themeButtonFg = colors.white,
    },
    {
        name = "PURPLE",
        pageBg = colors.black,
        headerBg = colors.purple,
        headerFg = colors.white,
        sectionBg = colors.magenta,
        sectionFg = colors.white,
        columnBg = colors.purple,
        columnFg = colors.white,
        rowA = colors.black,
        rowB = colors.gray,
        rowFg = colors.white,
        lineFg = colors.magenta,
        mutedFg = colors.lightGray,
        themeButtonBg = colors.magenta,
        themeButtonFg = colors.white,
    },
    {
        name = "CYAN",
        pageBg = colors.black,
        headerBg = colors.cyan,
        headerFg = colors.black,
        sectionBg = colors.lightBlue,
        sectionFg = colors.black,
        columnBg = colors.cyan,
        columnFg = colors.black,
        rowA = colors.black,
        rowB = colors.gray,
        rowFg = colors.white,
        lineFg = colors.lightBlue,
        mutedFg = colors.lightGray,
        themeButtonBg = colors.cyan,
        themeButtonFg = colors.black,
    },
    {
        name = "LIME",
        pageBg = colors.black,
        headerBg = colors.lime,
        headerFg = colors.black,
        sectionBg = colors.green,
        sectionFg = colors.black,
        columnBg = colors.lime,
        columnFg = colors.black,
        rowA = colors.black,
        rowB = colors.gray,
        rowFg = colors.white,
        lineFg = colors.lime,
        mutedFg = colors.lightGray,
        themeButtonBg = colors.lime,
        themeButtonFg = colors.black,
    },
    {
        name = "GRAY",
        pageBg = colors.black,
        headerBg = colors.gray,
        headerFg = colors.white,
        sectionBg = colors.lightGray,
        sectionFg = colors.black,
        columnBg = colors.gray,
        columnFg = colors.white,
        rowA = colors.black,
        rowB = colors.gray,
        rowFg = colors.white,
        lineFg = colors.lightGray,
        mutedFg = colors.lightGray,
        themeButtonBg = colors.gray,
        themeButtonFg = colors.white,
    },
    {
        name = "BROWN",
        pageBg = colors.black,
        headerBg = colors.brown,
        headerFg = colors.white,
        sectionBg = colors.orange,
        sectionFg = colors.black,
        columnBg = colors.brown,
        columnFg = colors.white,
        rowA = colors.black,
        rowB = colors.gray,
        rowFg = colors.white,
        lineFg = colors.orange,
        mutedFg = colors.lightGray,
        themeButtonBg = colors.brown,
        themeButtonFg = colors.white,
    },
    {
        name = "PINK",
        pageBg = colors.black,
        headerBg = colors.pink,
        headerFg = colors.black,
        sectionBg = colors.magenta,
        sectionFg = colors.white,
        columnBg = colors.pink,
        columnFg = colors.black,
        rowA = colors.black,
        rowB = colors.gray,
        rowFg = colors.white,
        lineFg = colors.pink,
        mutedFg = colors.lightGray,
        themeButtonBg = colors.pink,
        themeButtonFg = colors.black,
    },
}

return THEMES
